
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 26;
  public static final int LBRACKET = 17;
  public static final int UMINUS = 24;
  public static final int LPAREN = 15;
  public static final int GREATER = 33;
  public static final int SEMI = 20;
  public static final int INT = 2;
  public static final int LESS = 32;
  public static final int MINUS = 23;
  public static final int WRITE = 40;
  public static final int RPAREN = 16;
  public static final int OROR = 29;
  public static final int NOT = 27;
  public static final int GTGT = 37;
  public static final int BOOL = 3;
  public static final int COMMA = 19;
  public static final int ANDAND = 28;
  public static final int PLUS = 22;
  public static final int LESSEQ = 34;
  public static final int IF = 7;
  public static final int ID = 38;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 18;
  public static final int EQUAL = 21;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int EQEQ = 30;
  public static final int NUMBER = 43;
  public static final int CIN = 11;
  public static final int VOID = 4;
  public static final int INTLITERAL = 42;
  public static final int TIMES = 25;
  public static final int LBRACE = 13;
  public static final int ELSE = 8;
  public static final int COUT = 12;
  public static final int READ = 39;
  public static final int WHILE = 9;
  public static final int LTLT = 36;
  public static final int RBRACE = 14;
  public static final int GREATEREQ = 35;
  public static final int STRINGLITERAL = 41;
  public static final int FALSE = 6;
  public static final int NOTEQ = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BOOL",
  "VOID",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "CIN",
  "COUT",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "SEMI",
  "EQUAL",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "DIVIDE",
  "NOT",
  "ANDAND",
  "OROR",
  "EQEQ",
  "NOTEQ",
  "LESS",
  "GREATER",
  "LESSEQ",
  "GREATEREQ",
  "LTLT",
  "GTGT",
  "ID",
  "READ",
  "WRITE",
  "STRINGLITERAL",
  "INTLITERAL",
  "NUMBER"
  };
}

